---
deployment:
  tasks:
    - export DEPLOYPATH=/home/revlhiro/repo/blizz/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --optimize-autoloader --no-dev
    - npm ci
    - npm run build
    - php artisan key:generate --force
    - php artisan migrate --seed --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 755 storage/
    - chmod -R 755 bootstrap/cache/
