---
deployment:
  tasks:
    # Use current directory instead of assuming path
    - export DEPLOY_PATH=$(pwd)
    - echo "=== Blizz Ayurveda Deployment Started ==="
    - echo "Deploy path: $DEPLOY_PATH"
    - ls -la $DEPLOY_PATH
    
    # Ensure we're in the right directory
    - cd $DEPLOY_PATH
    
    # Set proper permissions first
    - echo "Setting permissions..."
    - chmod -R 755 storage/ || true
    - chmod -R 755 bootstrap/cache/ || true
    - chmod 644 .env* || true
    
    # Check PHP version
    - echo "PHP version:"
    - php -v || echo "PHP not found in PATH"
    
    # Try different PHP paths common in cPanel
    - export PHP_PATH=$(which php)
    - echo "PHP path: $PHP_PATH"
    - if [ -z "$PHP_PATH" ]; then export PHP_PATH="/usr/local/bin/php"; fi
    - if [ -z "$PHP_PATH" ]; then export PHP_PATH="/opt/cpanel/ea-php82/root/usr/bin/php"; fi
    
    # Composer installation
    - echo "Installing Composer dependencies..."
    - if command -v composer >/dev/null 2>&1; then 
        composer install --no-dev --optimize-autoloader --prefer-dist --no-interaction;
      else
        echo "Composer not found, skipping dependency installation";
      fi
    
    # Environment file setup
    - echo "Setting up environment file..."
    - if [ ! -f ".env" ]; then
        if [ -f ".env.example.production" ]; then
          cp .env.example.production .env;
          echo "Environment file created from production template";
        elif [ -f ".env.subdomain.template" ]; then
          cp .env.subdomain.template .env;
          echo "Environment file created from subdomain template";
        else
          cp .env.example .env;
          echo "Environment file created from example";
        fi
      else
        echo "Environment file already exists";
      fi
    
    # Laravel setup commands
    - echo "Generating application key..."
    - $PHP_PATH artisan key:generate --force || echo "Failed to generate app key"
    
    - echo "Creating storage link..."
    - $PHP_PATH artisan storage:link || echo "Failed to create storage link"
    
    - echo "Clearing caches..."
    - $PHP_PATH artisan config:clear || true
    - $PHP_PATH artisan route:clear || true
    - $PHP_PATH artisan view:clear || true
    - $PHP_PATH artisan cache:clear || true
    
    - echo "Running database migrations..."
    - $PHP_PATH artisan migrate --force || echo "Migration failed - check database config"
    
    - echo "Caching configurations..."
    - $PHP_PATH artisan config:cache || true
    - $PHP_PATH artisan route:cache || true
    - $PHP_PATH artisan view:cache || true
    
    - echo "Optimizing application..."
    - $PHP_PATH artisan optimize || true
    
    # Final permissions
    - echo "Setting final permissions..."
    - chmod -R 755 storage/ || true
    - chmod -R 755 bootstrap/cache/ || true
    
    - echo "=== Blizz Ayurveda Deployment Completed ==="
    - echo "Visit your subdomain to verify deployment"
